### PR TITLE
Adding my own implementation called speedrun.js

### PR DESCRIPTION
**Pull request by GreepTheSheep**
Hi, I actually working on a new library called speedrun.js, who is a Node.js implementation of this API. It would be nice too adding it in this file if you don't mind. Thanks in advance ^^

### CODE REVIEW

**Comment by DerKO9** [comment]
A js library would be really useful. I'm excited to check this out when its done!

**Comment by megadrive** [comment]
I think you should get to a v1 stage before adding it to the readme.

**Comment by GreepTheSheep** [comment]
> I think you should get to a v1 stage before adding it to the readme.

I'll do. I'll message when it's ready

**Comment by AnInternetTroll** [comment]
May I ask what's the difference between this library and [node-speedrun](https://github.com/SwitchbladeBot/node-speedrun)?

**Comment by GreepTheSheep** [comment]
> May I ask what's the difference between this library and [node-speedrun](https://github.com/SwitchbladeBot/node-speedrun)?

Never seen this lib
Also I just checked out and I see it uses classes. I'll try to make mine the simplest possible to be used by beginners (and to be integrated on [Discord.js](https://github.com/Discordjs/Discord.js) bots because I mostly work on this)

**Comment by DerKO9** [comment]
I think [node-speedrun](https://github.com/SwitchbladeBot/node-speedrun) should be added to the library list while we're talking about it.

**Comment by AnInternetTroll** [comment]
While node-speedrun doesn't have any functionality to get a game by abbreviation or by name how your library does with `
speedrun.games.getGameByAbbreviation('hl2')` it does have a function to get a game by ID `speedrun.games.get('j1npme6p')`. And both libraries do `speedrun.games.` so I don't see how yours is simpler. If anything you can make a Pull Request to node-speedrun to add new features instead of reinventing the wheel.

**Pull request closed without merging**
